export const categories = [
  { id: "marketplaces", name: "Маркетплейсы" },
  { id: "department", name: "Универмаги" },
  { id: "clothing", name: "Одежда" },
  { id: "footwear", name: "Обувь" },
  { id: "children", name: "Товары для детей" },
  { id: "supplements", name: "БАДы и витамины" },
  { id: "beauty", name: "Красота и парфюм" },
  { id: "electronics", name: "Электроника" },
  { id: "sports", name: "Спорт и outdoor" },
  { id: "home", name: "Дом и мебель" },
  { id: "auto", name: "Автозапчасти" },
  { id: "books", name: "Книги" },
  { id: "toys", name: "Игрушки" },
  { id: "hobby", name: "Хобби и коллекционные" },
]

export interface Marketplace {
  id: string
  name: string
  category: string
  description: string
  logo: string
  url: string
}

export const marketplaces: Marketplace[] = [
  // Маркетплейсы
  {
    id: "ebay",
    name: "Ebay",
    category: "marketplaces",
    description: "Всемирноизвестный маркетплейс с миллионами товаров от магазинов и частных лиц. Аукционы, Buy It Now, редкие коллекционные предметы.",
    logo: "ebay",
    url: "https://www.ebay.com",
  },
  {
    id: "amazon",
    name: "Amazon",
    category: "marketplaces",
    description: "Крупнейший маркетплейс США. Здесь найдётся всё — от айфонов до кукурузных хлопьев. Prime-доставка на склад OWAY за 1-2 дня.",
    logo: "amazon",
    url: "https://www.amazon.com",
  },
  {
    id: "walmart",
    name: "Walmart",
    category: "marketplaces",
    description: "Онлайн-маркетплейс сети супермаркетов Walmart. Ниже цены чем Amazon на товары для дома, детское питание, витамины.",
    logo: "walmart",
    url: "https://www.walmart.com",
  },
  {
    id: "target",
    name: "Target",
    category: "marketplaces",
    description: "Американский маркетплейс с фокусом на дизайн. Эксклюзивные коллаборации, товары для дома, одежда среднего сегмента.",
    logo: "target",
    url: "https://www.target.com",
  },
  {
    id: "newegg",
    name: "Newegg",
    category: "marketplaces",
    description: "Специализируется на компьютерном оборудовании и бытовой электронике. Часто выгоднее Amazon на комплектующие для ПК.",
    logo: "newegg",
    url: "https://www.newegg.com",
  },

  // Универмаги
  {
    id: "macys",
    name: "Macy's",
    category: "department",
    description: "Один из старейших универмагов США. Известен сезонными распродажами до -70%, программой Friends & Family (25% доп. скидка 4 раза в год).",
    logo: "macys",
    url: "https://www.macys.com",
  },
  {
    id: "nordstrom",
    name: "Nordstrom",
    category: "department",
    description: "Премиум-универмаг с отличным сервисом. Nordstrom Anniversary Sale в июле — лучшие скидки года.",
    logo: "nordstrom",
    url: "https://www.nordstrom.com",
  },
  {
    id: "kohls",
    name: "Kohl's",
    category: "department",
    description: "Средний сегмент, частые распродажи 50-70%. Kohl's Cash — бонусы $10 за каждые $50 покупок.",
    logo: "kohls",
    url: "https://www.kohls.com",
  },
  {
    id: "bloomingdales",
    name: "Bloomingdale's",
    category: "department",
    description: "Премиум-универмаг. Сестринская сеть Macy's но уровнем выше. Частые sample sale на дизайнерские бренды.",
    logo: "bloomingdales",
    url: "https://www.bloomingdales.com",
  },
  {
    id: "jcpenney",
    name: "JCPenney",
    category: "department",
    description: "Бюджетный универмаг. Глубокие скидки на одежду для всей семьи, постельное бельё, посуду.",
    logo: "jcpenney",
    url: "https://www.jcpenney.com",
  },
  {
    id: "saks",
    name: "Saks Fifth Avenue",
    category: "department",
    description: "Luxury-универмаг. Gucci, Prada, Chanel, Bottega Veneta. Saks Friends & Family — 25% скидка дважды в год.",
    logo: "saks",
    url: "https://www.saksfifthavenue.com",
  },
  {
    id: "neimanmarcus",
    name: "Neiman Marcus",
    category: "department",
    description: "Luxury-универмаг. Наравне с Saks. Известен Last Call распродажами 70-80%.",
    logo: "neimanmarcus",
    url: "https://www.neimanmarcus.com",
  },
  {
    id: "dillards",
    name: "Dillard's",
    category: "department",
    description: "Региональный универмаг (преимущественно Юг США). Премиум-бренды со скидками, частые sample sale.",
    logo: "dillards",
    url: "https://www.dillards.com",
  },

  // Одежда
  {
    id: "zara",
    name: "Zara",
    category: "clothing",
    description: "Испанский модный бренд. В США цены ниже чем в Европе и СНГ на 20-40%. Fast fashion, новые коллекции каждые 2 недели.",
    logo: "zara",
    url: "https://www.zara.com/us",
  },
  {
    id: "hm",
    name: "H&M",
    category: "clothing",
    description: "Шведский fast fashion. В США выгоднее из-за распродаж. Дизайнерские коллаборации — Mugler, Paco Rabanne.",
    logo: "hm",
    url: "https://www2.hm.com/en_us",
  },
  {
    id: "gap",
    name: "Gap",
    category: "clothing",
    description: "Базовая американская одежда. Качество выше чем у H&M, часто распродажи 40-60%.",
    logo: "gap",
    url: "https://www.gap.com",
  },
  {
    id: "oldnavy",
    name: "Old Navy",
    category: "clothing",
    description: "Младший бренд Gap. Очень выгодные цены на базовый гардероб для всей семьи.",
    logo: "oldnavy",
    url: "https://oldnavy.gap.com",
  },
  {
    id: "bananarepublic",
    name: "Banana Republic",
    category: "clothing",
    description: "Средний сегмент Gap Inc. Деловая одежда, качественные ткани.",
    logo: "bananarepublic",
    url: "https://bananarepublic.gap.com",
  },
  {
    id: "ralphlauren",
    name: "Ralph Lauren",
    category: "clothing",
    description: "Классический американский бренд. Polo Ralph Lauren — в США заметно дешевле чем в СНГ.",
    logo: "ralphlauren",
    url: "https://www.ralphlauren.com",
  },
  {
    id: "levis",
    name: "Levi's",
    category: "clothing",
    description: "Культовые американские джинсы. В США оригинальные модели 501/511/721 стоят $60-80, в СНГ — от $120.",
    logo: "levis",
    url: "https://www.levi.com",
  },
  {
    id: "abercrombie",
    name: "Abercrombie & Fitch",
    category: "clothing",
    description: "Американский кэжуал премиум-сегмента. Джинсы и свитера считаются одними из лучших в США.",
    logo: "abercrombie",
    url: "https://www.abercrombie.com",
  },
  {
    id: "hollister",
    name: "Hollister",
    category: "clothing",
    description: "Младший бренд Abercrombie для подростков. Доступные цены на кэжуал.",
    logo: "hollister",
    url: "https://www.hollisterco.com",
  },
  {
    id: "americaneagle",
    name: "American Eagle",
    category: "clothing",
    description: "Casual-бренд для молодёжи. Отличные джинсы средней цены, частые скидки 40-50%.",
    logo: "americaneagle",
    url: "https://www.ae.com",
  },
  {
    id: "forever21",
    name: "Forever 21",
    category: "clothing",
    description: "Ультра-бюджетный fast fashion. Платья и аксессуары от $10-20.",
    logo: "forever21",
    url: "https://www.forever21.com",
  },
  {
    id: "nordstromrack",
    name: "Nordstrom Rack",
    category: "clothing",
    description: "Outlet Nordstrom — премиум-бренды со скидкой 40-70%. Kate Spade, Michael Kors, Tory Burch.",
    logo: "nordstromrack",
    url: "https://www.nordstromrack.com",
  },

  // Обувь
  {
    id: "nike",
    name: "Nike",
    category: "footwear",
    description: "Культовые кроссовки. В США дешевле чем в СНГ на 30-50%, особенно лимитированные модели Air Max, Jordan.",
    logo: "nike",
    url: "https://www.nike.com",
  },
  {
    id: "adidas",
    name: "Adidas",
    category: "footwear",
    description: "Немецкий спортивный бренд. В США цены близки к европейским, часто выгодные модели Yeezy, Stan Smith, Samba.",
    logo: "adidas",
    url: "https://www.adidas.com/us",
  },
  {
    id: "footlocker",
    name: "Foot Locker",
    category: "footwear",
    description: "Крупнейший ретейлер кроссовок в США. Эксклюзивные дропы Nike, Jordan, Adidas.",
    logo: "footlocker",
    url: "https://www.footlocker.com",
  },
  {
    id: "dsw",
    name: "DSW",
    category: "footwear",
    description: "Designer Shoe Warehouse. Огромный выбор обуви со скидками, известные бренды по outlet-ценам.",
    logo: "dsw",
    url: "https://www.dsw.com",
  },
  {
    id: "zappos",
    name: "Zappos",
    category: "footwear",
    description: "Онлайн-магазин обуви с культовым сервисом. Бесплатная доставка и возврат по США (в OWAY полезно).",
    logo: "zappos",
    url: "https://www.zappos.com",
  },
  {
    id: "finishline",
    name: "Finish Line",
    category: "footwear",
    description: "Спортивная обувь и одежда. Частые распродажи Nike, Jordan, Adidas.",
    logo: "finishline",
    url: "https://www.finishline.com",
  },
  {
    id: "newbalance",
    name: "New Balance",
    category: "footwear",
    description: "Американский бренд кроссовок. Классические модели 574, 990. В США дешевле чем в СНГ вдвое.",
    logo: "newbalance",
    url: "https://www.newbalance.com",
  },
  {
    id: "allenedmonds",
    name: "Allen Edmonds",
    category: "footwear",
    description: "Премиум американская классическая обувь. Туфли ручной работы от $250 (в СНГ — от $500).",
    logo: "allenedmonds",
    url: "https://www.allenedmonds.com",
  },

  // Товары для детей
  {
    id: "carters",
    name: "Carter's",
    category: "children",
    description: "№1 бренд детской одежды в США. Распродажи 50-70% каждые 2 недели, комплекты от $10.",
    logo: "carters",
    url: "https://www.carters.com",
  },
  {
    id: "childrensplace",
    name: "The Children's Place",
    category: "children",
    description: "Бюджетный бренд детской одежды. Частые распродажи 70% на всё.",
    logo: "childrensplace",
    url: "https://www.childrensplace.com",
  },
  {
    id: "oshkosh",
    name: "OshKosh B'gosh",
    category: "children",
    description: "Американский бренд детской одежды с 1895 года. Прочные комбинезоны, школьная форма.",
    logo: "oshkosh",
    url: "https://www.oshkosh.com",
  },
  {
    id: "potterybarnkids",
    name: "Pottery Barn Kids",
    category: "children",
    description: "Премиум товары для детской комнаты. Кроватки, постельное, декор.",
    logo: "potterybarnkids",
    url: "https://www.potterybarnkids.com",
  },
  {
    id: "gymboree",
    name: "Gymboree",
    category: "children",
    description: "Детская одежда среднего сегмента. Яркие коллекции, качественные ткани.",
    logo: "gymboree",
    url: "https://www.gymboree.com",
  },
  {
    id: "gapkids",
    name: "Gap Kids",
    category: "children",
    description: "Детская линия Gap. Базовый гардероб качества Gap по частым распродажам.",
    logo: "gapkids",
    url: "https://www.gap.com/browse/division.do?cid=5683",
  },
  {
    id: "janieandjack",
    name: "Janie and Jack",
    category: "children",
    description: "Премиум детская одежда. Классические коллекции для праздников и повседневки.",
    logo: "janieandjack",
    url: "https://www.janieandjack.com",
  },

  // БАДы и витамины
  {
    id: "vitaminshoppe",
    name: "Vitamin Shoppe",
    category: "supplements",
    description: "Крупная сеть магазинов витаминов и БАДов. Широкий выбор, частые акции 2 по цене 1.",
    logo: "vitaminshoppe",
    url: "https://www.vitaminshoppe.com",
  },
  {
    id: "gnc",
    name: "GNC",
    category: "supplements",
    description: "Американская сеть спортивного питания и БАДов. Продукция собственной марки GNC Pro Performance.",
    logo: "gnc",
    url: "https://www.gnc.com",
  },
  {
    id: "iherb",
    name: "iHerb",
    category: "supplements",
    description: "Огромный каталог натуральных БАДов, витаминов, органической косметики. Скидки новым клиентам.",
    logo: "iherb",
    url: "https://www.iherb.com",
  },
  {
    id: "vitacost",
    name: "Vitacost",
    category: "supplements",
    description: "Онлайн-магазин витаминов. Часто дешевле iHerb на те же бренды (NOW, Jarrow, Solgar).",
    logo: "vitacost",
    url: "https://www.vitacost.com",
  },
  {
    id: "bodybuildingcom",
    name: "Bodybuilding.com",
    category: "supplements",
    description: "Специализируется на спортивном питании. Протеин, креатин, BCAA дешевле чем в СНГ в 2-3 раза.",
    logo: "bodybuildingcom",
    url: "https://www.bodybuilding.com",
  },
  {
    id: "swansonvitamins",
    name: "Swanson Vitamins",
    category: "supplements",
    description: "Собственная марка Swanson — дешевле большинства конкурентов при сопоставимом качестве.",
    logo: "swansonvitamins",
    url: "https://www.swansonvitamins.com",
  },
  {
    id: "nowfoods",
    name: "NOW Foods",
    category: "supplements",
    description: "Прямой магазин бренда NOW. Витамины, масла, эфиры от производителя.",
    logo: "nowfoods",
    url: "https://www.nowfoods.com",
  },

  // Красота и парфюм (OWAY принимает парфюм — это преимущество!)
  {
    id: "sephora",
    name: "Sephora",
    category: "beauty",
    description: "Крупнейшая сеть косметики в США. Эксклюзивы Fenty, Rare Beauty, Charlotte Tilbury. Beauty Insider программа.",
    logo: "sephora",
    url: "https://www.sephora.com",
  },
  {
    id: "ulta",
    name: "Ulta Beauty",
    category: "beauty",
    description: "Масс и прем косметика под одной крышей. Ulta Rewards даёт бесплатные товары.",
    logo: "ulta",
    url: "https://www.ulta.com",
  },
  {
    id: "victoriassecret",
    name: "Victoria's Secret",
    category: "beauty",
    description: "Культовое бельё и аромат. В США цены на 40-60% ниже чем в СНГ. Semi-Annual Sale дважды в год.",
    logo: "victoriassecret",
    url: "https://www.victoriassecret.com",
  },
  {
    id: "bathandbodyworks",
    name: "Bath & Body Works",
    category: "beauty",
    description: "Ароматические свечи, лосьоны, гели для душа. Легендарные распродажи Semi-Annual 75% off.",
    logo: "bathandbodyworks",
    url: "https://www.bathandbodyworks.com",
  },
  {
    id: "maccosmetics",
    name: "MAC Cosmetics",
    category: "beauty",
    description: "Профессиональная декоративная косметика. Помады, палетки теней, тональные средства.",
    logo: "maccosmetics",
    url: "https://www.maccosmetics.com",
  },
  {
    id: "sallybeauty",
    name: "Sally Beauty",
    category: "beauty",
    description: "Профессиональная косметика для волос и ногтей. OPI, Wella, Redken, CND.",
    logo: "sallybeauty",
    url: "https://www.sallybeauty.com",
  },
  {
    id: "lookfantastic",
    name: "Look Fantastic",
    category: "beauty",
    description: "Премиум косметика и парфюм. La Mer, Tom Ford, Creed, Dyson Airwrap.",
    logo: "lookfantastic",
    url: "https://www.lookfantastic.com",
  },
  {
    id: "thefragranceshop",
    name: "Fragrance X",
    category: "beauty",
    description: "Нишевая парфюмерия со скидками. Niche-бренды типа Tom Ford, Creed, Byredo дешевле масс-маркета.",
    logo: "thefragranceshop",
    url: "https://www.fragrancex.com",
  },

  // Электроника
  {
    id: "bestbuy",
    name: "Best Buy",
    category: "electronics",
    description: "Крупнейшая сеть электроники в США. iPhone, Samsung, ноутбуки, бытовая техника.",
    logo: "bestbuy",
    url: "https://www.bestbuy.com",
  },
  {
    id: "bhphoto",
    name: "B&H Photo",
    category: "electronics",
    description: "Специализация — фото и видео. Камеры Canon, Sony, Nikon, объективы, освещение. Часто дешевле Amazon.",
    logo: "bhphoto",
    url: "https://www.bhphotovideo.com",
  },
  {
    id: "applestore",
    name: "Apple Store",
    category: "electronics",
    description: "Официальный магазин Apple. В США iPhone, MacBook, iPad стоят на 20-40% дешевле чем в СНГ.",
    logo: "applestore",
    url: "https://www.apple.com/shop",
  },
  {
    id: "dell",
    name: "Dell",
    category: "electronics",
    description: "Прямой магазин Dell. Рабочие станции Precision, ноутбуки XPS, мониторы UltraSharp.",
    logo: "dell",
    url: "https://www.dell.com",
  },
  {
    id: "microcenter",
    name: "Micro Center",
    category: "electronics",
    description: "Комплектующие для ПК. Процессоры Intel/AMD часто на 10-20% дешевле чем у конкурентов.",
    logo: "microcenter",
    url: "https://www.microcenter.com",
  },
  {
    id: "hp",
    name: "HP Store",
    category: "electronics",
    description: "Прямой магазин HP. Принтеры, чернила, ноутбуки Pavilion, Envy, Omen.",
    logo: "hp",
    url: "https://www.hp.com/us-en/shop",
  },
  {
    id: "monoprice",
    name: "Monoprice",
    category: "electronics",
    description: "Кабели, HDMI, мониторы, аксессуары под собственной маркой. Цены в разы ниже брендовых аналогов.",
    logo: "monoprice",
    url: "https://www.monoprice.com",
  },
  {
    id: "bose",
    name: "Bose",
    category: "electronics",
    description: "Премиум аудио. Наушники QuietComfort, колонки SoundLink. В США дешевле чем в СНГ.",
    logo: "bose",
    url: "https://www.bose.com",
  },

  // Спорт и outdoor
  {
    id: "rei",
    name: "REI Co-op",
    category: "sports",
    description: "Outdoor и походное снаряжение премиум-сегмента. Palapas, Arc'teryx, Patagonia.",
    logo: "rei",
    url: "https://www.rei.com",
  },
  {
    id: "dicks",
    name: "Dick's Sporting Goods",
    category: "sports",
    description: "Крупнейшая сеть спорттоваров США. Одежда, обувь, инвентарь для всех видов спорта.",
    logo: "dicks",
    url: "https://www.dickssportinggoods.com",
  },
  {
    id: "underarmour",
    name: "Under Armour",
    category: "sports",
    description: "Американский спортивный бренд. В США цены на 40% ниже чем в СНГ.",
    logo: "underarmour",
    url: "https://www.underarmour.com",
  },
  {
    id: "academy",
    name: "Academy Sports",
    category: "sports",
    description: "Бюджетный спортмаг с огромным выбором. Рыбалка, охота, велоспорт, фитнес.",
    logo: "academy",
    url: "https://www.academy.com",
  },
  {
    id: "backcountry",
    name: "Backcountry",
    category: "sports",
    description: "Лыжи, сноуборд, походы, альпинизм. Премиум outdoor бренды.",
    logo: "backcountry",
    url: "https://www.backcountry.com",
  },
  {
    id: "moosejaw",
    name: "Moosejaw",
    category: "sports",
    description: "Outdoor снаряжение со скидками. The North Face, Patagonia, Arc'teryx.",
    logo: "moosejaw",
    url: "https://www.moosejaw.com",
  },
  {
    id: "patagonia",
    name: "Patagonia",
    category: "sports",
    description: "Премиум outdoor бренд. Куртки, пуховики, флис высшего качества. В США дешевле на 30-40%.",
    logo: "patagonia",
    url: "https://www.patagonia.com",
  },
  {
    id: "columbia",
    name: "Columbia",
    category: "sports",
    description: "Outdoor бренд средней цены. Куртки Omni-Heat, треккинговая обувь.",
    logo: "columbia",
    url: "https://www.columbia.com",
  },

  // Дом и мебель
  {
    id: "homedepot",
    name: "Home Depot",
    category: "home",
    description: "Крупнейшая сеть товаров для дома и ремонта. Инструменты Milwaukee, DeWalt, Makita.",
    logo: "homedepot",
    url: "https://www.homedepot.com",
  },
  {
    id: "ikeaUs",
    name: "IKEA US",
    category: "home",
    description: "Американский IKEA. Цены ниже чем в СНГ, но доставка — только мелкие товары через OWAY (мебель нет).",
    logo: "ikeaUs",
    url: "https://www.ikea.com/us/en",
  },
  {
    id: "bedbathandbeyond",
    name: "Bed Bath & Beyond",
    category: "home",
    description: "Товары для спальни, ванной, кухни. Постельное бельё, полотенца, посуда.",
    logo: "bedbathandbeyond",
    url: "https://www.bedbathandbeyond.com",
  },
  {
    id: "potterybarn",
    name: "Pottery Barn",
    category: "home",
    description: "Премиум товары для дома. Постельное, подушки, декор, посуда.",
    logo: "potterybarn",
    url: "https://www.potterybarn.com",
  },
  {
    id: "williamssonoma",
    name: "Williams Sonoma",
    category: "home",
    description: "Премиум кухня и еда. Le Creuset, All-Clad, Breville, KitchenAid.",
    logo: "williamssonoma",
    url: "https://www.williams-sonoma.com",
  },
  {
    id: "wayfair",
    name: "Wayfair",
    category: "home",
    description: "Онлайн-гипермаркет мебели и декора. Огромный выбор, частые скидки 70%.",
    logo: "wayfair",
    url: "https://www.wayfair.com",
  },
  {
    id: "crateandbarrel",
    name: "Crate & Barrel",
    category: "home",
    description: "Премиум декор и мебель. Современные коллекции для дома.",
    logo: "crateandbarrel",
    url: "https://www.crateandbarrel.com",
  },
  {
    id: "worldmarket",
    name: "World Market",
    category: "home",
    description: "Товары со всего мира — текстиль, декор, продукты, вино. Средний сегмент.",
    logo: "worldmarket",
    url: "https://www.worldmarket.com",
  },

  // Автозапчасти (НОВАЯ категория — высокий спрос из СНГ)
  {
    id: "rockauto",
    name: "RockAuto",
    category: "auto",
    description: "Крупнейший онлайн-магазин автозапчастей. Огромный каталог по VIN-номеру, цены ниже дилерских на 40-60%.",
    logo: "rockauto",
    url: "https://www.rockauto.com",
  },
  {
    id: "autozone",
    name: "AutoZone",
    category: "auto",
    description: "Крупная сеть магазинов автозапчастей США. Аккумуляторы, масла, фильтры, тормоза.",
    logo: "autozone",
    url: "https://www.autozone.com",
  },
  {
    id: "oreilly",
    name: "O'Reilly Auto Parts",
    category: "auto",
    description: "Конкурент AutoZone. Запчасти для иномарок и американских марок, программа лояльности O'Rewards.",
    logo: "oreilly",
    url: "https://www.oreillyauto.com",
  },
  {
    id: "advanceauto",
    name: "Advance Auto Parts",
    category: "auto",
    description: "Третья крупная сеть автозапчастей. Часто лучшие акции на моторные масла и тормозные колодки.",
    logo: "advanceauto",
    url: "https://www.advanceautoparts.com",
  },
  {
    id: "partsgeek",
    name: "PartsGeek",
    category: "auto",
    description: "Онлайн-склад автозапчастей. Поиск по VIN, цены ниже розничных.",
    logo: "partsgeek",
    url: "https://www.partsgeek.com",
  },
  {
    id: "tirerack",
    name: "Tire Rack",
    category: "auto",
    description: "Специализация — шины и колёса. Лучший выбор в США. Тесты, рейтинги, быстрая доставка.",
    logo: "tirerack",
    url: "https://www.tirerack.com",
  },
  {
    id: "summitracing",
    name: "Summit Racing",
    category: "auto",
    description: "Тюнинг и performance запчасти. Выхлопы, турбины, подвеска для спортивных машин.",
    logo: "summitracing",
    url: "https://www.summitracing.com",
  },
  {
    id: "4wheelparts",
    name: "4 Wheel Parts",
    category: "auto",
    description: "Offroad и 4x4 запчасти. Лифты, бамперы, лебёдки, шины для внедорожников.",
    logo: "4wheelparts",
    url: "https://www.4wheelparts.com",
  },
  {
    id: "jegs",
    name: "JEGS",
    category: "auto",
    description: "High-performance запчасти. Двигатели, трансмиссии, тормозные системы для спорта.",
    logo: "jegs",
    url: "https://www.jegs.com",
  },
  {
    id: "carid",
    name: "CARiD",
    category: "auto",
    description: "Аксессуары, автозапчасти, тюнинг. Огромный выбор по марке и модели.",
    logo: "carid",
    url: "https://www.carid.com",
  },

  // Книги
  {
    id: "barnesandnoble",
    name: "Barnes & Noble",
    category: "books",
    description: "Крупнейшая сеть книжных США. Новинки, бестселлеры, коллекционные издания.",
    logo: "barnesandnoble",
    url: "https://www.barnesandnoble.com",
  },
  {
    id: "thriftbooks",
    name: "ThriftBooks",
    category: "books",
    description: "Подержанные книги в отличном состоянии. Цены от $3.99.",
    logo: "thriftbooks",
    url: "https://www.thriftbooks.com",
  },
  {
    id: "abebooks",
    name: "AbeBooks",
    category: "books",
    description: "Редкие и коллекционные книги со всего мира. Первые издания, подписанные копии.",
    logo: "abebooks",
    url: "https://www.abebooks.com",
  },
  {
    id: "powells",
    name: "Powell's Books",
    category: "books",
    description: "Легендарный портлендский книжный. Новые и подержанные книги, редкие издания.",
    logo: "powells",
    url: "https://www.powells.com",
  },

  // Игрушки
  {
    id: "toysrus",
    name: "Toys R Us",
    category: "toys",
    description: "Крупнейший магазин игрушек США. Классика возвращается после банкротства с новыми точками.",
    logo: "toysrus",
    url: "https://www.toysrus.com",
  },
  {
    id: "legostore",
    name: "LEGO Store US",
    category: "toys",
    description: "Официальный магазин LEGO. Эксклюзивные наборы, VIP-программа, выгоднее чем Amazon.",
    logo: "legostore",
    url: "https://www.lego.com/en-us",
  },
  {
    id: "mattel",
    name: "Mattel Shop",
    category: "toys",
    description: "Барби, Hot Wheels, Fisher-Price. Эксклюзивы недоступные в других магазинах.",
    logo: "mattel",
    url: "https://shop.mattel.com",
  },
  {
    id: "buildabear",
    name: "Build-A-Bear",
    category: "toys",
    description: "Уникальные плюшевые мишки ручной сборки. Популярный подарок.",
    logo: "buildabear",
    url: "https://www.buildabear.com",
  },
  {
    id: "americangirl",
    name: "American Girl",
    category: "toys",
    description: "Премиум куклы с историями. Культовый американский бренд для девочек.",
    logo: "americangirl",
    url: "https://www.americangirl.com",
  },

  // Хобби и коллекционные
  {
    id: "michaels",
    name: "Michaels",
    category: "hobby",
    description: "Товары для творчества и рукоделия. Бисер, пряжа, краски, художественные материалы.",
    logo: "michaels",
    url: "https://www.michaels.com",
  },
  {
    id: "hobbylobby",
    name: "Hobby Lobby",
    category: "hobby",
    description: "Конкурент Michaels. Скидки 40% на разные отделы еженедельно.",
    logo: "hobbylobby",
    url: "https://www.hobbylobby.com",
  },
  {
    id: "joann",
    name: "JOANN",
    category: "hobby",
    description: "Ткани, выкройки, шитьё, пряжа. Лучший выбор для рукодельниц.",
    logo: "joann",
    url: "https://www.joann.com",
  },
  {
    id: "blick",
    name: "Blick Art Materials",
    category: "hobby",
    description: "Профессиональные художественные материалы. Краски, бумага, холсты от лучших брендов.",
    logo: "blick",
    url: "https://www.dickblick.com",
  },
  {
    id: "guitarcenter",
    name: "Guitar Center",
    category: "hobby",
    description: "Крупнейший музыкальный магазин США. Гитары, усилители, педали, студийное оборудование.",
    logo: "guitarcenter",
    url: "https://www.guitarcenter.com",
  },
]

export function getMarketplaceById(id: string): Marketplace | undefined {
  return marketplaces.find((m) => m.id === id)
}
